name: dwcas-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (${{ matrix.goos }}/${{ matrix.goarch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux&&amd64
          - runner: ubuntu-latest
            goos: linux
            goarch: amd64

          # darwin&&arm64
          - runner: macos-latest
            goos: darwin
            goarch: arm64

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Test (default)
        run: go test ./...

      - name: Test (dwcas_llsc)
        if: matrix.goarch == 'arm64'
        run: go test -tags=dwcas_llsc ./...

  coverage:
    name: Coverage (linux/amd64) + Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Test (coverage)
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          fail_ci_if_error: true
